name: Build

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        options:
          - "Artifact"
          - "Release"
      version:
        type: string
        required: false

jobs:
  build:
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64, riscv64]
        exclude:
          - os: windows
            arch: riscv64
          - os: darwin
            arch: riscv64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
      - name: Build
        run: |
          go build -ldflags="-s"
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: ico-encoder-${{ matrix.os }}-${{ matrix.arch }}
          path: ./ico-encoder*

  release:
    if: github.event.inputs.choice == 'Release'
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: ico-encoder-*
          path: artifacts
      - name: Rename
        run: |
          mkdir ./outputs
          find ./artifacts -type f | while read file; do
            base_with_ext="${file##*/}"
            ext="${base_with_ext##*.}"
            artifact_name=$(basename "$(dirname "$file")")

            new_name="$artifact_name.$ext"
            if [[ "$base_with_ext" == "$ext" ]]; then
              new_name="$artifact_name"
            fi

            mv "$file" "./outputs/$new_name"
          done
      - uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          name: Release v${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}
          files: |
            ./outputs/*
